--------------------------------------------------------
--  File created - Sunday-December-18-2022   
--------------------------------------------------------
REM INSERTING into TEST02.CHINHANH
SET DEFINE OFF;
Insert into TEST02.CHINHANH (MACHINHANH,DIACHI,SDT) values ('CN01','Quan Go Vap','0962562451');
Insert into TEST02.CHINHANH (MACHINHANH,DIACHI,SDT) values ('CN02','Quan 1','0792626426');
REM INSERTING into TEST02.LOAITIEC
SET DEFINE OFF;
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT01','Tiec sinh nhat',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT02','Tiec thoi noi',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT03','Tiec cuoi',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT04','Tiec cuoi',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT05','Su kien ra mat dien thoai',15);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT06','Tiec sinh nhat',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT07','Le tri an',5);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT08','Tiec dinh hon',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT09','Tiec cuoi',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT10','Tiec cuoi',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT11','Tiec cuoi',20);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT12','Tiec thoi noi',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT13','Su kien hop co dong',15);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT14','Tiec hop lop',5);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT15','Tiec sinh nhat',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT16','Su kien ra mat xe hoi',15);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT17','Tiec hop lop',5);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT18','Tiec thoi noi',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT19','Tiec cuoi nam',10);
Insert into TEST02.LOAITIEC (MALT,TENLT,YCMINBAN) values ('LT20','Tiec cuoi',20);
REM INSERTING into TEST02.MD_ADDITIONAL_PROPERTIES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_APPLICATIONFILES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_APPLICATIONS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_CATALOGS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_CODE_REGEX
SET DEFINE OFF;
Insert into TEST02.MD_CODE_REGEX (ID,REGEX,DESCRIPTION) values (1,'\#[A-Z1-9\@\#\_]','Temporary tables');
Insert into TEST02.MD_CODE_REGEX (ID,REGEX,DESCRIPTION) values (2,'INSERT','Insert statements');
Insert into TEST02.MD_CODE_REGEX (ID,REGEX,DESCRIPTION) values (3,'SELECT','Select statements');
Insert into TEST02.MD_CODE_REGEX (ID,REGEX,DESCRIPTION) values (4,'UPDATE','Update Statements');
Insert into TEST02.MD_CODE_REGEX (ID,REGEX,DESCRIPTION) values (5,'DELETE','Delete Statements');
REM INSERTING into TEST02.MD_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_CONNECTIONS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_CONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_CONSTRAINT_DETAILS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_DERIVATIVES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_FILE_ARTIFACTS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_GROUPS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_GROUP_MEMBERS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_GROUP_PRIVILEGES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_INDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_INDEX_DETAILS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_MIGR_DEPENDENCY
SET DEFINE OFF;
REM INSERTING into TEST02.MD_MIGR_PARAMETER
SET DEFINE OFF;
REM INSERTING into TEST02.MD_MIGR_WEAKDEP
SET DEFINE OFF;
REM INSERTING into TEST02.MD_NUMROW$SOURCE
SET DEFINE OFF;
REM INSERTING into TEST02.MD_NUMROW$TARGET
SET DEFINE OFF;
REM INSERTING into TEST02.MD_OTHER_OBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_PACKAGES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_PARTITIONS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_PRIVILEGES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_PROJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_REGISTRY
SET DEFINE OFF;
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('PACKAGE','MD_META',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('PACKAGE','MIGRATION_TRANSFORMER',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('PACKAGE','MIGRATION',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('PACKAGE','MIGRATION_REPORT',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_STORED_PROGRAMS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_TABLE_TRIGGERS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_VIEWS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_CONNECTIONS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_VIEW_TRIGGERS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_CATALOGS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_SCHEMA',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_TABLES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_PARTITIONS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_CAPTURED_SQL',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_CATALOG_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_SCHEMA_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_TABLES_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_PROGRAMS_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_VIEW_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_COLUMN_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_COLUMNDT_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_CONSTRAINTS_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_INDEX_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_TRIGGER_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_ALL_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_DERIVED_DETAILS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_DERIVATIVES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('VIEW','MGV_SCRATCH_DERIVATIVES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('SEQUENCE','DBOBJECTID_SEQUENCE',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_CATALOGS','DATABASE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MIGRLOG',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_GROUP_PRIVILEGES','GROUP PRIVILEGE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_USER_PRIVILEGES','USER_PRIVILEGE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MIGR_DATATYPE_TRANSFORM_MAP',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MIGR_DATATYPE_TRANSFORM_RULE',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_MIGR_PARAMETER','PARAMETER');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_MIGR_DEPENDENCY','DEPENDENCY');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_MIGR_WEAKDEP','DEPENDENCY');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MIGR_GENERATION_ORDER',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_CONSTRAINT_DETAILS','CONSTRAINT');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_CONSTRAINTS','CONSTRAINT');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_REPOVERSIONS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_OTHER_OBJECTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_SYNONYMS','SYNONYM');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MIGRATION_RESERVED_WORDS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_PACKAGES','PACKAGE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_SEQUENCES','SEQUENCE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_DERIVATIVES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_ADDITIONAL_PROPERTIES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_TABLESPACES','TABLESPACE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_STORED_PROGRAMS','PROCEDURE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_TRIGGERS','TRIGGER');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_USER_DEFINED_DATA_TYPES','UDT');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_PRIVILEGES','PRIVILEGE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_GROUP_MEMBERS','GROUP MEMBER');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_GROUPS','GROUP');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_INDEX_DETAILS','INDEX');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_PROJECTS','PROJECT');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_CONNECTIONS','MODEL');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_USERS','USER');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_SCHEMAS','SCHEMA');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_TABLES','TABLE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_VIEWS','VIEW');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_INDEXES','INDEX');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_COLUMNS','COLUMN');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_PARTITIONS','PARTITION');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_APPLICATIONS','TABLE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_APPLICATIONFILES','TABLE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_FILE_ARTIFACTS','TABLE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_NUMROW$SOURCE','NUMROW$SOURCE');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','MD_NUMROW$TARGET','NUMROW$TARGET');
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSDATABASES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSUSERS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSOBJECTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSCOLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSTYPES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSCOMMENTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSINDEXES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SYB12_SYSCONSTRAINTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_DATABASES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_SCHEMATA',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_TABLE_PRIVILEGES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_CHECK_CONSTRAINTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_COLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_DATABASE_PRINCIPALS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_DATABASE_ROLE_MEMBERS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_FOREIGN_KEY_COLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_FOREIGN_KEYS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_IDENTITY_COLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_INDEX_COLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_INDEXES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_OBJECTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_SCHEMAS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_SERVER_PRINCIPALS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_SQL_MODULES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_TABLES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_TYPES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_DEFAULT_CONSTRAINTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','SS2K5_SYSPROPERTIES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','OBJECTIDLIST',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','NAME_AND_COUNT_T',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','NAME_AND_COUNT_ARRAY',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','NAMELIST',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_FILTER',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_FILTER_SET',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_REPORT_DETAIL_ROW',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_REPORT_DETAIL_TABLE',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_REPORT_SUM_ROW',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TYPE','MIGR_REPORT_SUM_TABLE',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_CHECK',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_INDC',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_INDDET',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_INDEXES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_PKEYS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_PROCS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_TABLES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_TRIGS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_VIEWS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_VDEFNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_OFFLINE_FKEYS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_LOG',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_DATABASES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_TABLES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_COLUMNS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_TABLETEXT',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_TRIGGERS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_UDTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_INDICES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_FKEYS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_IDXCONSTRAINTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_ALL_RI_PARENTS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_PROCEDURES',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_SHOWTBLCHECKS',null);
Insert into TEST02.MD_REGISTRY (OBJECT_TYPE,OBJECT_NAME,DESC_OBJECT_NAME) values ('TABLE','STAGE_TERADATA_JOININDICES',null);
REM INSERTING into TEST02.MD_REPOVERSIONS
SET DEFINE OFF;
Insert into TEST02.MD_REPOVERSIONS (REVISION) values (65);
REM INSERTING into TEST02.MD_SCHEMAS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_SEQUENCES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_STORED_PROGRAMS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_SYNONYMS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_TABLES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_TABLESPACES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_TARGET_ALL_ERRORS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_TARGET_ALL_OBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_TRIGGERS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_USERS
SET DEFINE OFF;
REM INSERTING into TEST02.MD_USER_DEFINED_DATA_TYPES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_USER_PRIVILEGES
SET DEFINE OFF;
REM INSERTING into TEST02.MD_VIEWS
SET DEFINE OFF;
REM INSERTING into TEST02.MIGRATION_RESERVED_WORDS
SET DEFINE OFF;
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SHARE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('LEVEL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('RAW');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DROP');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('BETWEEN');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('FROM');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DESC');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('OPTION');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('PRIOR');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('LONG');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('THEN');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DEFAULT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ALTER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('IS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INTO');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('MINUS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INTEGER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NUMBER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('GRANT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('IDENTIFIED');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ALL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('TO');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ORDER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ON');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('FLOAT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('HAVING');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CLUSTER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NOWAIT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('RESOURCE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ANY');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('TABLE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INDEX');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('FOR');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('UPDATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('WHERE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CHECK');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SMALLINT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('WITH');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DELETE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('BY');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ASC');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('REVOKE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('LIKE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SIZE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('RENAME');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NOCOMPRESS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NULL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('GROUP');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('VALUES');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('AS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('IN');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('VIEW');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('EXCLUSIVE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('COMPRESS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SYNONYM');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SELECT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INSERT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('EXISTS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NOT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('TRIGGER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ELSE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CREATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INTERSECT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('PCTFREE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DISTINCT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CONNECT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SET');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('MODE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('OF');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('UNIQUE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('VARCHAR2');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('VARCHAR');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('LOCK');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('OR');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CHAR');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('DECIMAL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('UNION');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('PUBLIC');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('AND');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('START');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('USER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('VALIDATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('COMMENT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('UID');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ROWNUM');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('AUDIT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ACCESS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('FILE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('OFFLINE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SESSION');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('PRIVILEGES');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ADD');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('COLUMN');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('CURRENT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('IMMEDIATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INCREMENT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('INITIAL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('MAXEXTENTS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('MLSLABEL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('MODIFY');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('NOAUDIT');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ONLINE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ROW');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ROWID');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('ROWS');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SUCCESSFUL');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('SYSDATE');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('WHENEVER');
Insert into TEST02.MIGRATION_RESERVED_WORDS (KEYWORD) values ('COMMIT');
REM INSERTING into TEST02.MIGRLOG
SET DEFINE OFF;
REM INSERTING into TEST02.MIGR_DATATYPE_TRANSFORM_MAP
SET DEFINE OFF;
REM INSERTING into TEST02.MIGR_DATATYPE_TRANSFORM_RULE
SET DEFINE OFF;
REM INSERTING into TEST02.MIGR_GENERATION_ORDER
SET DEFINE OFF;
REM INSERTING into TEST02.NHANVIEN
SET DEFINE OFF;
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV11','Le Thi Phi Yen',to_date('25-DEC-96','DD-MON-RR'),'293456892','Sang',35000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV12','Phan Hoang Yen',to_date('04-MAR-97','DD-MON-RR'),'793571916','Toi',45000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV13','Nguyen Huu Thanh',to_date('22-APR-89','DD-MON-RR'),'345221875','Toi',45000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV14','Nguyen Thi Hoang Hao',to_date('07-SEP-90','DD-MON-RR'),'238765618','Sang',35000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV15','Mai Thanh Danh',to_date('15-JUL-00','DD-MON-RR'),'962642189','Toi',45000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV16','Le Tran Anh Loan',to_date('29-JAN-02','DD-MON-RR'),'864627698','Toi',45000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV17','Nguyen Minh Tuan',to_date('04-APR-93','DD-MON-RR'),'185372638','Sang',35000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV18','Truong Minh Chau',to_date('28-FEB-90','DD-MON-RR'),'973536374','Sang',35000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV19','Phan Thi Kim Duyen',to_date('29-NOV-00','DD-MON-RR'),'963531213','Toi',45000,'CN02');
Insert into TEST02.NHANVIEN (MANV,HOTEN,NGSINH,SDT,CALV,MUCLUONG,MACHINHANH) values ('NV20','Tran Thi Phi Yen',to_date('21-MAR-99','DD-MON-RR'),'976344142','Toi',45000,'CN02');
REM INSERTING into TEST02.PHUCVU
SET DEFINE OFF;
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV11','MT20',5,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV12','MT01',4,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV13','MT04',4,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV14','MT16',3,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV15','MT02',4,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV16','MT18',5,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV17','MT13',2,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV18','MT14',5,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV19','MT08',4,'CN02');
Insert into TEST02.PHUCVU (MANV,MATIEC,THOIGIAN,MACHINHANH) values ('NV20','MT11',4,'CN02');
REM INSERTING into TEST02.SANH
SET DEFINE OFF;
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS04','Sanh D','Vuong',30,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS05','Sanh E','Tron',40,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS08','Sanh H','Vuong',40,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS09','Sanh J','Vuong',50,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS11','Sanh L','Vuong',80,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS13','Sanh W','Tron',50,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS15','Sanh T','Vuong',10,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS16','Sanh Y','Vuong',40,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS19','Sanh M','Vuong',10,'CN02');
Insert into TEST02.SANH (MASANH,TENSANH,LOAIBAN,SUCCHUA,MACHINHANH) values ('MS20','Sanh N','Tron',20,'CN02');
REM INSERTING into TEST02.SS2K5_CHECK_CONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_DATABASES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_DATABASE_PRINCIPALS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_DATABASE_ROLE_MEMBERS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_DEFAULT_CONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_FOREIGN_KEYS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_FOREIGN_KEY_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_IDENTITY_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_INDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_INDEX_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_OBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_SCHEMAS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_SCHEMATA
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_SERVER_PRINCIPALS
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_SQL_MODULES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_SYSPROPERTIES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_TABLES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_TABLE_PRIVILEGES
SET DEFINE OFF;
REM INSERTING into TEST02.SS2K5_TYPES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_MIGRLOG
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SERVERDETAIL
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_CHECK_CONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_DATABASES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_DB_PRINCIPALS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_DB_ROLE_MEMBERS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_DT_CONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_FN_KEYS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_FN_KEY_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_IDENTITY_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_INDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_INDEX_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_OBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_SCHEMAS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_SCHEMATA
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_SERVER_PRINCIPALS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_SQL_MODULES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_SYSPROPERTIES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_TABLES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_TABLE_PRIVILEGES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SS2K5_TYPES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSCOLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSCOMMENTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSCONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSDATABASES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSINDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSOBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSREFERENCES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSTYPES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_SYB12_SYSUSERS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_ALL_RI_PARENTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_COLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_DATABASES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_FKEYS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_IDXCONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_INDICES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_JOININDICES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_LOG
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_CHECK
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_FKEYS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_INDC
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_INDDET
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_INDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_PKEYS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_PROCS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_TABLES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_TRIGS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_VDEFNS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_OFFLINE_VIEWS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_PROCEDURES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_SHOWTBLCHECKS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_TABLES
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_TABLETEXT
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_TRIGGERS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TERADATA_UDTS
SET DEFINE OFF;
REM INSERTING into TEST02.STAGE_TRANSLATEDSQL
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSCOLUMNS
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSCOMMENTS
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSCONSTRAINTS
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSDATABASES
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSINDEXES
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSOBJECTS
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSTYPES
SET DEFINE OFF;
REM INSERTING into TEST02.SYB12_SYSUSERS
SET DEFINE OFF;
REM INSERTING into TEST02.TIEC_NV
SET DEFINE OFF;
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT01','CN02','MS01',to_date('01-FEB-20','DD-MON-RR'),to_date('01-FEB-20','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT02','CN02','MS02',to_date('03-JAN-20','DD-MON-RR'),to_date('03-JAN-20','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT04','CN02','MS04',to_date('21-NOV-19','DD-MON-RR'),to_date('21-NOV-19','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT08','CN02','MS08',to_date('06-SEP-18','DD-MON-RR'),to_date('06-SEP-18','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT11','CN02','MS11',to_date('22-APR-22','DD-MON-RR'),to_date('22-APR-22','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT13','CN02','MS13',to_date('25-MAR-22','DD-MON-RR'),to_date('25-MAR-22','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT14','CN02','MS14',to_date('01-NOV-22','DD-MON-RR'),to_date('01-NOV-22','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT16','CN02','MS16',to_date('03-MAY-19','DD-MON-RR'),to_date('03-MAY-19','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT18','CN02','MS18',to_date('04-FEB-19','DD-MON-RR'),to_date('04-FEB-19','DD-MON-RR'));
Insert into TEST02.TIEC_NV (MATIEC,MACHINHANH,MASANH,TGBD,TGKT) values ('MT20','CN02','MS20',to_date('27-APR-22','DD-MON-RR'),to_date('27-APR-22','DD-MON-RR'));
REM INSERTING into TEST02.TIEC_QL
SET DEFINE OFF;
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT01','Tran Ngoc Linh','LT01','MS01',11,11000000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT02','Truong My Hanh ','LT02','MS02',10,5000000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT03','Huynh Thi Kim Trieu ','LT03','MS03',25,125000000,'Da bi huy ');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT04','Do Thanh Xuan ','LT04','MS04',30,150000000,'Da dien ra ');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT05','Truong Thi My Hien ','LT05','MS05',20,60000000,'Da bi huy ');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT06','Tran Ngoc Hoai','LT06','MS06',11,11000000,'Da dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT07','Tran Minh Man ','LT07','MS07',10,5000000,'Da bi huy');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT08','Nguyen Trung Nghia','LT08','MS08',20,60000000,'Da dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT09','Tran Minh Thuc ','LT09','MS09',40,200000000,'Da dien ra ');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT10','Nguyen Linh Dan ','LT10','MS10',33,165000000,'Da bi huy');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT11','Le Hoang Viet','LT11','MS11',25,125000000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT12','Lam Tra My','LT12','MS12',15,7500000,'Da bi huy');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT13','Nguyen Tan Phat','LT13','MS13',30,210000000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT14','Tran Van Anh','LT14','MS14',6,1800000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT15','Le Minh Anh','LT15','MS15',15,15000000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT16','Nguyen Minh Nhut','LT16','MS16',18,180000000,'Da bi huy');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT17','Mai Ha Giang','LT17','MS17',8,2400000,'Da dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT18','Ha Thu Hien','LT18','MS18',11,5500000,'Da dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT19','Nguyen To Loan','LT19','MS19',19,9500000,'Dang dien ra');
Insert into TEST02.TIEC_QL (MATIEC,CHUTIEC,MALT,MASANH,SOBAN,GIA,TINHTRANG) values ('MT20','Nguyen Le Manh Khoa','LT20','MS20',29,145000000,'Dang dien ra');
